### ISSUE TITLE
Unable to import Polymer from nylon

### ISSUE THREAD

**Issue by FrancyJGLisboa** [Palashio/nylon#35]
I've installed nylon in a conda env with, I believe, all necessary dependencies for the library. However, when I code from nylon import Polymer, I get an error saying Polymer is not a module.

**Comment by Palashio** [comment]
could you paste in your initialization code? @FrancyJGLisboa

**Comment by FrancyJGLisboa** [comment]
It is just

import pandas as pd 
import numpy as np
from nylon import Polymer

Then 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Polymer' from 'nylon' (/Users/grointelligence/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/nylon/__init__.py)

My conda env:

# Name                    Version                   Build  Channel
alembic                   1.6.5                    pypi_0    pypi
altair                    4.1.0                    pypi_0    pypi
ansiwrap                  0.8.4                    pypi_0    pypi
anyio                     3.3.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.2                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
asgiref                   3.4.1                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
autograd                  1.3                      pypi_0    pypi
autograd-gamma            0.5.0                    pypi_0    pypi
ax-platform               0.2.0                    pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
base58                    2.1.0                    pypi_0    pypi
black                     21.7b0                   pypi_0    pypi
bleach                    4.0.0                    pypi_0    pypi
blinker                   1.4                      pypi_0    pypi
blis                      0.7.4                    pypi_0    pypi
boruta                    0.3                      pypi_0    pypi
botorch                   0.5.0                    pypi_0    pypi
bottleneck                1.3.2                    pypi_0    pypi
ca-certificates           2020.10.14                    0    anaconda
catalogue                 1.0.0                    pypi_0    pypi
catboost                  0.26.1                   pypi_0    pypi
certifi                   2020.6.20                py38_0    anaconda
cffi                      1.14.6                   pypi_0    pypi
charset-normalizer        2.0.4                    pypi_0    pypi
click                     8.0.1                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coloredlogs               14.0                     pypi_0    pypi
colorlover                0.3.0                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
croniter                  0.3.37                   pypi_0    pypi
cufflinks                 0.17.3                   pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cymem                     2.0.5                    pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
dagster                   0.12.5                   pypi_0    pypi
dask                      2021.7.2                 pypi_0    pypi
dask-glm                  0.2.0                    pypi_0    pypi
dask-ml                   1.9.0                    pypi_0    pypi
dask-xgboost              0.2.0                    pypi_0    pypi
databricks-cli            0.14.3                   pypi_0    pypi
datatable                 1.0.0                    pypi_0    pypi
debugpy                   1.4.1                    pypi_0    pypi
decorator                 5.0.9                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
distributed               2021.7.2                 pypi_0    pypi
docker                    5.0.0                    pypi_0    pypi
docstring-parser          0.10                     pypi_0    pypi
easyprocess               0.3                      pypi_0    pypi
entrypoint2               0.2.4                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
fastai                    2.5.0                    pypi_0    pypi
fastapi                   0.68.0                   pypi_0    pypi
fastcore                  1.3.25                   pypi_0    pypi
fastdownload              0.0.3                    pypi_0    pypi
fastprogress              1.0.0                    pypi_0    pypi
fbprophet                 0.7                      pypi_0    pypi
flask                     2.0.1                    pypi_0    pypi
formulaic                 0.2.4                    pypi_0    pypi
fsspec                    2021.7.0                 pypi_0    pypi
funcy                     1.16                     pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gensim                    3.8.3                    pypi_0    pypi
gitdb                     4.0.7                    pypi_0    pypi
gitpython                 3.1.18                   pypi_0    pypi
gpytorch                  1.5.0                    pypi_0    pypi
greenlet                  1.1.0                    pypi_0    pypi
groclient                 1.139.1                  pypi_0    pypi
grpcio-health-checking    1.39.0                   pypi_0    pypi
gunicorn                  20.1.0                   pypi_0    pypi
h11                       0.12.0                   pypi_0    pypi
h2o                       3.32.1.5                 pypi_0    pypi
h5py                      3.3.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
htmlmin                   0.1.12                   pypi_0    pypi
humanfriendly             9.2                      pypi_0    pypi
hyperopt                  0.2.5                    pypi_0    pypi
idna                      3.2                      pypi_0    pypi
imagehash                 4.2.1                    pypi_0    pypi
imbalanced-learn          0.7.0                    pypi_0    pypi
interface-meta            1.2.3                    pypi_0    pypi
ipykernel                 6.0.3                    pypi_0    pypi
ipympl                    0.7.0                    pypi_0    pypi
ipython                   7.26.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
itsdangerous              2.0.1                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
json5                     0.9.6                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyter-server            1.10.2                   pypi_0    pypi
jupyterlab                3.1.4                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.6.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
jupytext                  1.11.4                   pypi_0    pypi
kats                      0.1.0                    pypi_0    pypi
keras                     2.4.3                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
kmodes                    0.11.0                   pypi_0    pypi
libcxx                    10.0.0                        1    anaconda
libedit                   3.1.20191231         h1de35cc_1    anaconda
libffi                    3.3                  hb1e8313_2    anaconda
lifelines                 0.26.0                   pypi_0    pypi
lightgbm                  3.2.1                    pypi_0    pypi
lineedit                  0.1.6                    pypi_0    pypi
llvmlite                  0.36.0                   pypi_0    pypi
locket                    0.2.1                    pypi_0    pypi
mako                      1.1.4                    pypi_0    pypi
markdown-it-py            1.1.0                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
marshmallow               3.13.0                   pypi_0    pypi
marshmallow-oneofschema   3.0.1                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
matrixprofile             1.1.10                   pypi_0    pypi
mdit-py-plugins           0.2.8                    pypi_0    pypi
missingno                 0.5.0                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mizani                    0.7.3                    pypi_0    pypi
mlflow                    1.19.0                   pypi_0    pypi
mlxtend                   0.18.0                   pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
multimethod               1.4                      pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
murmurhash                1.0.5                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
natsort                   7.1.1                    pypi_0    pypi
nbclassic                 0.3.1                    pypi_0    pypi
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.1.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1    anaconda
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.6.2                    pypi_0    pypi
ngboost                   0.3.12                   pypi_0    pypi
nltk                      3.6.2                    pypi_0    pypi
notebook                  6.4.2                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.21.1                   pypi_0    pypi
nylon                     0.0.2                    pypi_0    pypi
openai                    0.10.2                   pypi_0    pypi
openpyxl                  3.0.7                    pypi_0    pypi
openssl                   1.1.1h               haf1e3a3_0    anaconda
packaging                 21.0                     pypi_0    pypi
palettable                3.3.0                    pypi_0    pypi
pandas                    1.3.1                    pypi_0    pypi
pandas-flavor             0.2.0                    pypi_0    pypi
pandas-profiling          3.0.0                    pypi_0    pypi
pandas-stubs              1.2.0.1                  pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
papermill                 2.3.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
partd                     1.2.0                    pypi_0    pypi
pathspec                  0.9.0                    pypi_0    pypi
patsy                     0.5.1                    pypi_0    pypi
pendulum                  2.1.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
phik                      0.12.0                   pypi_0    pypi
photonai                  2.1.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.3.1                    pypi_0    pypi
pip                       20.2.4                   py38_0    anaconda
plac                      1.1.3                    pypi_0    pypi
plotly                    5.1.0                    pypi_0    pypi
plotnine                  0.8.0                    pypi_0    pypi
ppscore                   1.2.0                    pypi_0    pypi
prefect                   0.15.3                   pypi_0    pypi
preshed                   3.0.5                    pypi_0    pypi
prettytable               2.1.0                    pypi_0    pypi
prometheus-client         0.11.0                   pypi_0    pypi
prometheus-flask-exporter 0.18.2                   pypi_0    pypi
prompt-toolkit            3.0.19                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pyaml                     20.4.0                   pypi_0    pypi
pyarrow                   5.0.0                    pypi_0    pypi
pycaret                   2.3.3                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pydantic                  1.8.2                    pypi_0    pypi
pydeck                    0.6.2                    pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pyjanitor                 0.21.0                   pypi_0    pypi
pyldavis                  3.3.1                    pypi_0    pypi
pymannkendall             1.4.2                    pypi_0    pypi
pymodm                    0.4.3                    pypi_0    pypi
pymongo                   3.12.0                   pypi_0    pypi
pynndescent               0.5.4                    pypi_0    pypi
pyod                      0.9.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.18.0                   pypi_0    pypi
python                    3.8.1                h359304d_1    anaconda
python-box                5.3.0                    pypi_0    pypi
python-dateutil           2.8.2                    pypi_0    pypi
python-editor             1.0.4                    pypi_0    pypi
python-graphviz           0.17                     pypi_0    pypi
python-slugify            5.0.2                    pypi_0    pypi
pytorch-ranger            0.1.1                    pypi_0    pypi
pyts                      0.11.0                   pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pytzdata                  2020.1                   pypi_0    pypi
pyunpack                  0.2.2                    pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.2.1                   pypi_0    pypi
querystring-parser        1.2.4                    pypi_0    pypi
radian                    0.5.11                   pypi_0    pypi
rchitect                  0.3.32                   pypi_0    pypi
readline                  7.0                  h1de35cc_5    anaconda
regex                     2021.8.3                 pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
requests-unixsocket       0.2.0                    pypi_0    pypi
rich                      10.7.0                   pypi_0    pypi
rx                        1.6.1                    pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scikit-misc               0.1.4                    pypi_0    pypi
scikit-optimize           0.8.1                    pypi_0    pypi
scikit-plot               0.3.7                    pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
send2trash                1.7.1                    pypi_0    pypi
setuptools                50.3.0           py38h0dc7051_1    anaconda
shap                      0.39.0                   pypi_0    pypi
siuba                     0.0.25                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sklearn-pandas            2.2.0                    pypi_0    pypi
sktime                    0.7.0                    pypi_0    pypi
slicer                    0.0.7                    pypi_0    pypi
smart-open                5.1.0                    pypi_0    pypi
smmap                     4.0.0                    pypi_0    pypi
sniffio                   1.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
spacy                     2.3.7                    pypi_0    pypi
sqlalchemy                1.4.22                   pypi_0    pypi
sqlite                    3.33.0               hffcf06c_0    anaconda
sqlparse                  0.4.1                    pypi_0    pypi
srsly                     1.0.5                    pypi_0    pypi
starlette                 0.14.2                   pypi_0    pypi
statsmodels               0.12.2                   pypi_0    pypi
streamlit                 0.86.0                   pypi_0    pypi
stumpy                    1.9.2                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tangled-up-in-unicode     0.1.0                    pypi_0    pypi
tblib                     1.7.0                    pypi_0    pypi
tenacity                  8.0.1                    pypi_0    pypi
terminado                 0.10.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
textblob                  0.15.3                   pypi_0    pypi
textwrap3                 0.9.2                    pypi_0    pypi
thinc                     7.4.5                    pypi_0    pypi
threadpoolctl             2.2.0                    pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0    anaconda
toml                      0.10.2                   pypi_0    pypi
tomli                     1.2.1                    pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
toposort                  1.6                      pypi_0    pypi
torch-optimizer           0.1.0                    pypi_0    pypi
torchvision               0.10.0                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
tsai                      0.2.18                   pypi_0    pypi
tsfresh                   0.18.0                   pypi_0    pypi
typeguard                 2.12.1                   pypi_0    pypi
typing-compat             0.1.0                    pypi_0    pypi
typing-extensions         3.10.0.0                 pypi_0    pypi
tzlocal                   2.1                      pypi_0    pypi
ujson                     4.0.2                    pypi_0    pypi
umap-learn                0.5.1                    pypi_0    pypi
unicodecsv                0.14.1                   pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
uvicorn                   0.14.0                   pypi_0    pypi
validators                0.18.2                   pypi_0    pypi
visions                   0.7.1                    pypi_0    pypi
wasabi                    0.8.2                    pypi_0    pypi
watchdog                  2.1.3                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.1.1                    pypi_0    pypi
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.35.1                     py_0    anaconda
widgetsnbextension        3.5.1                    pypi_0    pypi
wordcloud                 1.8.1                    pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
xgboost                   1.4.2                    pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xlsxwriter                1.4.5                    pypi_0    pypi
xz                        5.2.5                h1de35cc_0    anaconda
yellowbrick               1.3.post1                pypi_0    pypi
zict                      2.0.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3    anaconda
(mlenv) ➜  mlenv

**Comment by FrancyJGLisboa** [comment]
It is working now. I was installing nylon and not nylon-ai in my conda env. After updating the env with nylon-ai it worked

**Comment by Palashio** [comment]
sounds good, let me know if you need any assistance.
